{{- if .Values.ingress.enabled }}
{{- $fullName := include "frontend.fullname" . -}}
{{- $svcPort := .Values.service.ports.frontend -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
  annotations:
    nginx.org/mergeable-ingress-type: "minion"
    nginx.org/location-snippets: |
      index /index.html;
      rewrite ^((?!.(js|css|png|svg|jpg|woff|woff2)).)*$ /index.html break;
      proxy_intercept_errors on;
      error_page 404 =200 /index.html;
      {{- .Values.ingress.cspSnippet | nindent 6}}
    {{- with .Values.ingress.annotations }}
    {{- range $key, $value := . }}
    {{ $key }}: {{ tpl $value $ | quote }}
    {{- end }}
    {{- end }}
spec:
  ingressClassName: {{ tpl .Values.ingress.className . }}
  rules:
    - host: {{ default .Values.global.domainName .Values.ingress.domainName }} 
      http:
        paths:
          - pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
            path: /
---
kind: Service
apiVersion: v1
metadata:
  name: openreplay-tracker
spec:
  type: ExternalName
  externalName: static.openreplay.com
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: openreplay-tracker-ingress
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
  annotations:
    nginx.org/mergeable-ingress-type: "minion"
    nginx.org/ssl-services: "openreplay-tracker"
    nginx.org/client-max-body-size: "8m"
    nginx.org/proxy-buffering: "true"
    nginx.org/location-snippets: |
      rewrite ^/script/(.*)/openreplay(.*).js$ /$1/openreplay$2.js break;
      proxy_ssl_name static.openreplay.com;
      proxy_ssl_server_name on;
      proxy_set_header Host static.openreplay.com;
    {{- with .Values.ingress.annotations }}
    {{- range $key, $value := . }}
    {{ $key }}: {{ tpl $value $ | quote }}
    {{- end }}
    {{- end }}
spec:
  ingressClassName: {{ tpl .Values.ingress.className . }}
  rules:
    - host: {{ default .Values.global.domainName .Values.ingress.domainName }} 
      http:
        paths:
          - pathType: Prefix
            backend:
              service:
                name: openreplay-tracker
                port:
                  number: 443
            path: /script/
{{- end }}
