{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "frontend.fullname" . }}-master
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
  annotations:
    nginx.org/mergeable-ingress-type: "master"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    # Pass through X-Forwarded headers from upstream proxy (Cloudflare, LB, etc.)
    nginx.org/proxy-set-headers: "X-Forwarded-Proto, X-Forwarded-Port"
spec:
  ingressClassName: "{{ tpl .Values.ingress.className . }}" 
  tls:
    - hosts:
        - {{ default .Values.global.domainName .Values.ingress.domainName }}
      {{- if .Values.ingress.tls.secretName}}
      secretName: {{ .Values.ingress.tls.secretName }}
      {{- end}}
  rules:
    - host: {{ default .Values.global.domainName .Values.ingress.domainName }}
{{- end }}
