{{- if .Values.ingress.enabled }}
{{- $fullName := include "frontend.fullname" . -}}
{{- $svcPort := .Values.service.ports.frontend -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
  annotations:
  {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
    nginx.ingress.kubernetes.io/configuration-snippet: |
      index /index.html;
      rewrite ^((?!.(js|css|png|svg|jpg|woff|woff2)).)*$ /index.html break;
      proxy_intercept_errors on; # see frontend://nginx.org/en/docs/frontend/ngx_frontend_proxy_module.html#proxy_intercept_errors
      error_page 404 =200 /index.html;
      {{- .Values.ingress.cspSnippet | nindent 6}}
spec:
  ingressClassName: "{{ tpl .Values.ingress.className . }}" 
  tls:
    - hosts:
        - {{ default .Values.global.domainName .Values.ingress.domainName }}
      {{- if .Values.ingress.tls.secretName}}
      secretName: {{ .Values.ingress.tls.secretName }}
      {{- end}}
  rules:
    - host: {{ default .Values.global.domainName .Values.ingress.domainName }} 
      http:
        paths:
          - pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
            path: /(.*)
          - backend:
              service:
                name: frontend-openreplay
                port:
                  number: 8080
            path: /(api|assist|ws-assist)/(private|sockets-list|sockets-live|peers)(.*)
            pathType: Prefix
---
kind: Service
apiVersion: v1
metadata:
  name: openreplay-tracker
spec:
  type: ExternalName
  externalName: static.openreplay.com
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: openreplay-tracker-ingress
  annotations:
  {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
    nginx.ingress.kubernetes.io/backend-protocol: https
    nginx.ingress.kubernetes.io/upstream-vhost: static.openreplay.com
    nginx.ingress.kubernetes.io/rewrite-target: '/$1/openreplay$2.js'
    nginx.ingress.kubernetes.io/proxy-body-size: 8m
    nginx.ingress.kubernetes.io/proxy-buffering: "on"
    nginx.ingress.kubernetes.io/server-snippet: |
      proxy_ssl_name static.openreplay.com;
      proxy_ssl_server_name on;
spec:
  ingressClassName: "{{ tpl .Values.ingress.className . }}" 
  tls:
    - hosts:
        - {{ .Values.global.domainName }}
      {{- if .Values.ingress.tls.secretName}}
      secretName: {{ .Values.ingress.tls.secretName }}
      {{- end}}
  rules:
    - host: {{ .Values.global.domainName }} 
      http:
        paths:
          - path: /script/(.*)/openreplay(.*).js
            pathType: Prefix
            backend:
              service:
                name: openreplay-tracker
                port:
                  number: 443
{{- end }}
