apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.9.2
  creationTimestamp: null
  name: apdospolicies.appprotectdos.f5.com
spec:
  group: appprotectdos.f5.com
  names:
    kind: APDosPolicy
    listKind: APDosPoliciesList
    plural: apdospolicies
    singular: apdospolicy
  preserveUnknownFields: false
  scope: Namespaced
  versions:
    - name: v1beta1
      schema:
        openAPIV3Schema:
          type: object
          description: APDosPolicy is the Schema for the APDosPolicy API
          properties:
            apiVersion:
              description: 'APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
              type: string
            kind:
              description: 'Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
              type: string
            metadata:
              type: object
            spec:
              type: object
              description: APDosPolicySpec defines the desired state of APDosPolicy
              properties:
                mitigation_mode:
                  enum:
                    - "standard"
                    - "conservative"
                    - "none"
                  default: "standard"
                  type: string
                signatures:
                  enum:
                    - "on"
                    - "off"
                  default: "on"
                  type: string
                bad_actors:
                  enum:
                    - "on"
                    - "off"
                  default: "on"
                  type: string
                automation_tools_detection:
                  enum:
                    - "on"
                    - "off"
                  default: "on"
                  type: string
                tls_fingerprint:
                  enum:
                    - "on"
                    - "off"
                  default: "on"
                  type: string
      served: true
      storage: true
