apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.9.2
  creationTimestamp: null
  name: apdoslogconfs.appprotectdos.f5.com
spec:
  group: appprotectdos.f5.com
  names:
    kind: APDosLogConf
    listKind: APDosLogConfList
    plural: apdoslogconfs
    singular: apdoslogconf
  preserveUnknownFields: false
  scope: Namespaced
  versions:
    - name: v1beta1
      schema:
        openAPIV3Schema:
          description: APDosLogConf is the Schema for the APDosLogConfs API
          properties:
            apiVersion:
              description: 'APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
              type: string
            kind:
              description: 'Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
              type: string
            metadata:
              type: object
            spec:
              description: APDosLogConfSpec defines the desired state of APDosLogConf
              properties:
                content:
                  properties:
                    format:
                      enum:
                        - splunk
                        - arcsight
                        - user-defined
                      type: string
                    format_string:
                      type: string
                    max_message_size:
                      pattern: ^([1-9]|[1-5][0-9]|6[0-4])k$
                      type: string
                  type: object
                filter:
                  properties:
                    traffic-mitigation-stats:
                      enum:
                        - none
                        - all
                      default: all
                      type: string
                    bad-actors:
                      pattern: ^(none|all|top ([1-9]|[1-9][0-9]|[1-9][0-9]{2,4}|100000))$
                      default: top 10
                      type: string
                    attack-signatures:
                      pattern: ^(none|all|top ([1-9]|[1-9][0-9]|[1-9][0-9]{2,4}|100000))$
                      default: top 10
                      type: string
                  type: object
              type: object
          type: object
      served: true
      storage: true
