apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kafka.labels" . | nindent 4 }}
    {{- include "kafka.componentLabels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  sessionAffinity: None
  ports:
    {{- if .Values.listeners.client.enabled }}
    - name: tcp-client
      port: {{ .Values.service.client.port }}
      protocol: TCP
      targetPort: kafka-client
      nodePort: null
    {{- end }}
  selector:
    {{- include "kafka.selectorLabels" . | nindent 4 }}
    {{- include "kafka.componentLabels" . | nindent 4 }}
