{{- if .Values.serviceAccount.create -}}
# Template Parameters:
#
# COMMENT=
# NAMESPACE=kube-system
# NAME=clickhouse-operator
#
# Setup ServiceAccount
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "altinity-clickhouse-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    clickhouse.altinity.com/chop: 0.18.1
    {{- include "altinity-clickhouse-operator.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end -}}
