apiVersion: v1
kind: Service
metadata:
  name: {{ include "utilities.fullname" . }}
  labels:
    {{- include "utilities.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range $key, $val := .Values.service.ports }}
    - port: {{ $val }}
      targetPort: {{ $key }}
      protocol: TCP
      name: {{ $key }}
    {{- end}}
  selector:
    {{- include "utilities.selectorLabels" . | nindent 4 }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "utilities.fullname" . }}-headless
  labels:
    {{- include "utilities.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    {{- range $key, $val := .Values.service.ports }}
    - port: {{ $val }}
      targetPort: {{ $key }}
      protocol: TCP
      name: {{ $key }}
    {{- end}}
  selector:
    {{- include "utilities.selectorLabels" . | nindent 4 }}
