---
# defaults file for openreplay
app_name: ""
db_name: ""
db_list:
  - "minio"
  - "postgresql"
  - "redis"
  - "clickhouse"
  - "kafka"

env:
  alerts:
    ch_host: "clickhouse.db.svc.cluster.local"
    ch_port: "9000"
  chalice:
    ch_host: "clickhouse.db.svc.cluster.local"
    ch_port: "9000"
    LICENSE_KEY: "{{ enterprise_edition_license }}"
