namespace: app
image:
  repository: rg.fr-par.scw.cloud/foss
  name: alerts
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

imagePullSecrets:
  - name: aws-registry

service:
  type: ClusterIP
  port: 9000

resources:
  limits:
    cpu: 256m
    memory: 512Mi
  requests:
    cpu: 1m
    memory: 1Mi

env:
  pg_host: postgresql.db.svc.cluster.local
  pg_port: 5432
  pg_dbname: postgres
  pg_user: postgres
  pg_password: asayerPostgres
  ch_host: clickhouse.db.svc.cluster.local
  ch_port: 9000
  EMAIL_HOST: ''
  EMAIL_PORT: '587'
  EMAIL_USER: ''
  EMAIL_PASSWORD: ''
  EMAIL_USE_TLS: 'true'
  EMAIL_USE_SSL: 'false'
  EMAIL_SSL_KEY: ''
  EMAIL_SSL_CERT: ''
  EMAIL_FROM: OpenReplay<do-not-reply@openreplay.com>
  SITE_URL: ''
  S3_HOST: 'http://minio.db.svc.cluster.local:9000'
  S3_KEY: minios3AccessKeyS3cr3t
  S3_SECRET: m1n10s3CretK3yPassw0rd
  AWS_DEFAULT_REGION: us-east-1
  LICENSE_KEY: ""
  PYTHONUNBUFFERED: '0'
  version_number: '1.3.6'
