namespace: app
image:
  repository: rg.fr-par.scw.cloud/foss
  name: storage
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

imagePullSecrets:
  - name: aws-registry

service:
  type: ClusterIP
  port: 9000

resources:
  limits:
    cpu: 512m
    memory: 512Mi
  requests:
    cpu: 1m
    memory: 1Mi

pvc:
  # PVC Created from filesink.yaml
  create: false
  name: hostPath
  storageClassName: nfs
  volumeName: nfs
  mountPath: /mnt/efs
  hostMountPath: /openreplay/storage/nfs
  storageSize: 5Gi

env:
  AWS_ENDPOINT: http://minio.db.svc.cluster.local:9000
  AWS_ACCESS_KEY_ID: "minios3AccessKeyS3cr3t"
  AWS_SECRET_ACCESS_KEY: "m1n10s3CretK3yPassw0rd"
  AWS_REGION_WEB: us-east-1
  AWS_REGION_IOS: us-east-1
  S3_BUCKET_WEB: mobs
  S3_BUCKET_IOS: mobs
  #
  REDIS_STRING: redis-master.db.svc.cluster.local:6379
  KAFKA_SERVERS: kafka.db.svc.cluster.local:9092
  KAFKA_USE_SSL: false
  LICENSE_KEY: ""
  FS_CLEAN_HRS: 24
