root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -tags=dev -o ./tmp/api ./cmd/api"
bin = "tmp/api"
include_ext = ["go"]
exclude_dir = ["tmp", "vendor"]
full_bin = "bash -c 'export $(grep -v '^#' .env | xargs) && ./tmp/api'"

